language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm

node_js: 12

git:
  depth: 3

script:
  - yarn build

notifications:
  slack: cursotravispl-oj69982:80chAOzXqStXjwMnI1wVXoOv
  email:
    recipients:
      - lgfigueroah98@gmail.com
      - lgfh98123@gmail.com
    on_success: always
    on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: 'Deploy del proyecto'
  on:
    branch: strapi-travis
